# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academia.actividad')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': '02.2 - Registro de Asistencias',
                'db_table': 'core_asistencia',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
