# Generated by Django 5.2.5 on 2026-04-04 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_initial'),
        ('asistencia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='clase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_sesion', to='academia.cronograma'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='actividad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academia.actividad'),
        ),
    ]
