# Generated by Django 5.2.5 on 2026-04-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InscripcionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado', models.CharField(choices=[('pendiente', 'Pendiente de Evaluar'), ('aprobado', 'Aprobado / Ascenso'), ('desaprobado', 'Desaprobado'), ('ausente', 'Ausente')], default='pendiente', max_length=20)),
                ('nota_tecnica', models.PositiveIntegerField(blank=True, help_text='Puntaje 0-100', null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('procesado', models.BooleanField(default=False, help_text='Indica si ya se aplicó el ascenso en el perfil')),
            ],
            options={
                'verbose_name': 'Candidato a Examen',
                'verbose_name_plural': '06.2 - Candidatos e Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='MesaExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('lugar', models.CharField(help_text='Sede o Dirección del evento', max_length=200)),
                ('maestro_invitado', models.CharField(blank=True, help_text='Para maestros externos a la app', max_length=200)),
                ('esta_abierta', models.BooleanField(default=True, help_text='Permite inscripciones')),
                ('finalizada', models.BooleanField(default=False, help_text='Marca el evento como cerrado')),
            ],
            options={
                'verbose_name': 'Mesa de Examen',
                'verbose_name_plural': '06.1 - Mesas de Examen',
                'ordering': ['-fecha'],
            },
        ),
    ]
