# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examenes', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionexamen',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_examenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionexamen',
            name='grado_a_aspirar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='usuarios.grado'),
        ),
        migrations.AddField(
            model_name='inscripcionexamen',
            name='grado_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='usuarios.grado'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='examinadores',
            field=models.ManyToManyField(limit_choices_to={'es_profe': True}, related_name='mesas_examinadoras', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionexamen',
            name='mesa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='examenes.mesaexamen'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionexamen',
            unique_together={('mesa', 'alumno')},
        ),
    ]
