# Generated by Django 5.1.2 on 2026-04-20 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examenes', '0002_initial'),
        ('ventas', '0007_alter_pago_tipo_cierrecaja'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcionexamen',
            name='costo_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Examen'),
        ),
        migrations.AddField(
            model_name='inscripcionexamen',
            name='pago',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscripcion_examen', to='ventas.pago'),
        ),
        migrations.AddField(
            model_name='mesaexamen',
            name='precio_inscripcion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo base del examen para esta mesa', max_digits=10, verbose_name='Precio Base de Inscripción'),
        ),
    ]
