# Generated by Django 5.2.5 on 2026-03-27 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Mensual')),
                ('precio_clase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Clase Suelta')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': 'Actividades',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='dni',
            field=models.CharField(blank=True, max_length=15, verbose_name='DNI'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='domicilio',
            field=models.CharField(blank=True, max_length=255, verbose_name='Domicilio'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='localidad',
            field=models.CharField(blank=True, max_length=150, verbose_name='Localidad'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('mercadopago', 'Mercado Pago'), ('efectivo', 'En Efectivo')], max_length=20),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='core.actividad'),
        ),
        migrations.AddField(
            model_name='pago',
            name='actividad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.actividad'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='actividades',
            field=models.ManyToManyField(blank=True, related_name='alumnos', to='core.actividad'),
        ),
    ]
