# Generated by Django 5.2.5 on 2026-03-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_actividad_usuario_dni_usuario_domicilio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacion',
            name='actividades',
            field=models.ManyToManyField(blank=True, related_name='locaciones', to='core.actividad'),
        ),
    ]
