# Generated by Django 5.2.5 on 2026-03-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_locacion_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacion',
            name='mapa_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Maps'),
        ),
    ]
