# Generated by Django 5.2.5 on 2026-03-30 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_locacion_mapa_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='mercado_pago_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='mercado_pago_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
