# Generated by Django 5.2.5 on 2026-03-30 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pago_mercado_pago_id_pago_mercado_pago_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], max_length=2)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['dia', 'hora_inicio'],
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MP Access Token'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mp_public_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='MP Public Key'),
        ),
        migrations.CreateModel(
            name='ClaseProgramada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='core.actividad')),
                ('locacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='core.locacion')),
                ('profesor', models.ForeignKey(limit_choices_to={'es_profe': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL)),
                ('horarios', models.ManyToManyField(related_name='clases_asignadas', to='core.horario')),
            ],
            options={
                'verbose_name': 'Clase Programada',
                'verbose_name_plural': 'Clases Programadas',
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='clase_programada',
            field=models.ForeignKey(blank=True, help_text='Clase específica a la cual pertenece este pago (Sede + Actividad + Horario).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='core.claseprogramada'),
        ),
    ]
