# Generated by Django 5.2.5 on 2026-03-30 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_horario_usuario_mp_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='alergias',
            field=models.TextField(blank=True, verbose_name='Alergias Conocidas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apto_medico',
            field=models.FileField(blank=True, null=True, upload_to='aptos_medicos/', verbose_name='Certificado Apto Médico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='condiciones_medicas',
            field=models.TextField(blank=True, verbose_name='Condiciones Médicas'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, max_length=120, verbose_name='Nombre Contacto Emergencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfono Contacto Emergencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_ingreso_real',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso a la Asociación'),
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado', models.CharField(max_length=100, verbose_name='Grado Alcanzado')),
                ('fecha', models.DateField(verbose_name='Fecha del Examen')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Detalles')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to=settings.AUTH_USER_MODEL)),
                ('examinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_tomados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examen / Graduación',
                'verbose_name_plural': 'Exámenes y Graduaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
