# Generated by Django 5.2.5 on 2026-03-30 05:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_usuario_alergias_usuario_apto_medico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Producto',
                'verbose_name_plural': 'Categorías de Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago/Conf'), ('pagado', 'Pagado - A Preparar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('mercadopago', 'Mercado Pago'), ('efectivo', 'En Efectivo')], max_length=20)),
                ('cuotas', models.IntegerField(default=1)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pedidos/')),
                ('mercado_pago_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_status', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, help_text='% de ganancia para el profesor', max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0, help_text='Calculado automáticamente', max_digits=10)),
                ('backorder', models.BooleanField(default=False, help_text='Algún producto se compró sin stock y requiere reposición rápida')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_tienda', to=settings.AUTH_USER_MODEL)),
                ('profesor_venta', models.ForeignKey(blank=True, help_text='Profesor que recibirá comisión por esta venta.', limit_choices_to={'es_profe': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_tienda_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido de Tienda',
                'verbose_name_plural': 'Pedidos de Tienda',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True, help_text='Si es Falso, se oculta de la tienda')),
                ('permite_backorder', models.BooleanField(default=False, help_text='Permitir comprar aunque el stock sea 0')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.producto')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
            },
        ),
    ]
