# Generated by Django 5.2.5 on 2026-03-30 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categoriaproducto_pedido_producto_pedidoitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Categoría de Contenido',
                'verbose_name_plural': 'Categorías de Contenido',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='biblioteca/documentos/')),
                ('descargable', models.BooleanField(default=False, help_text='Si es Falso, el alumno solo podrá verlo en la app sin un botón de descarga expuesto.')),
                ('nivel_acceso', models.CharField(choices=[('todos', 'Público / Todos los Alumnos'), ('principiante', 'Solo Principiantes y superior'), ('intermedio', 'Solo Intermedios y superior'), ('avanzado', 'Solo Avanzados / Maestros')], default='todos', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='core.categoriacontenido')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='VideoTutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('youtube_id', models.CharField(help_text='ID del video de YouTube (ej. dQw4w9WgXcQ de https://www.youtube.com/watch?v=dQw4w9WgXcQ)', max_length=50)),
                ('nivel_acceso', models.CharField(choices=[('todos', 'Público / Todos los Alumnos'), ('principiante', 'Solo Principiantes y superior'), ('intermedio', 'Solo Intermedios y superior'), ('avanzado', 'Solo Avanzados / Maestros')], default='todos', max_length=20)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.categoriacontenido')),
            ],
            options={
                'verbose_name': 'Video Tutorial',
                'verbose_name_plural': 'Videos Tutoriales',
                'ordering': ['-fecha_subida'],
            },
        ),
    ]
