# Generated by Django 5.2.5 on 2026-03-31 19:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_categoriacontenido_documento_videotutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='fecha_vencimiento_cuota',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento de Cuota'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='uuid_carnet',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
