# Generated by Django 5.2.5 on 2026-03-31 19:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_fecha_vencimiento_cuota_usuario_uuid_carnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='uuid_carnet',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
