# Generated by Django 5.2.5 on 2026-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_usuario_uuid_carnet'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cuotas_maximas',
            field=models.IntegerField(default=1, verbose_name='Cuotas Máximas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión que se lleva el profesor por vender este producto específico.', max_digits=5, verbose_name='Porcentaje de Comisión Profe'),
        ),
    ]
