# Generated by Django 5.2.5 on 2026-03-31 23:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_producto_cuotas_maximas_producto_porcentaje_comision'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='autorizacion_tesoreria_activa',
            field=models.BooleanField(default=False, help_text='Interruptor de seguridad. Si es falso, el delegado no podrá entrar al panel de tesorería.', verbose_name='Autorización Tesorería Activa'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_acceso_total',
            field=models.BooleanField(default=False, help_text='Control absoluto sobre toda la plataforma (Dios).', verbose_name='Acceso Total (Superadministrador)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_gestion_academia',
            field=models.BooleanField(default=False, help_text='Biblioteca de videos y documentos.', verbose_name='Gestión de Academia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_gestion_alumnos',
            field=models.BooleanField(default=False, help_text='Inscripciones, morosidad, aptos médicos.', verbose_name='Gestión de Alumnos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_gestion_sedes',
            field=models.BooleanField(default=False, help_text='Locaciones, clases, horarios, exámenes.', verbose_name='Gestión de Sedes'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_gestion_tesoreria',
            field=models.BooleanField(default=False, help_text='Todo el dinero de la asociación.', verbose_name='Gestión de Tesorería (Global)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='rol_gestion_tienda',
            field=models.BooleanField(default=False, help_text='Productos, stock, pedidos.', verbose_name='Gestión de Tienda'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tesorero_autorizado',
            field=models.ForeignKey(blank=True, help_text='Persona que gestionará las comisiones de este profesor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesoreria_admin_de', to=settings.AUTH_USER_MODEL, verbose_name='Tesorero Autorizado (Delegado)'),
        ),
    ]
