# Generated by Django 5.2.5 on 2026-03-31 23:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_usuario_autorizacion_tesoreria_activa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claseprogramada',
            name='porcentaje_comision_asistente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión que se lleva el asistente por las ventas registradas en esta clase.', max_digits=5, verbose_name=' % Comisión Asistente'),
        ),
        migrations.AddField(
            model_name='claseprogramada',
            name='profesor_asistente',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_profe': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_asistente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedido',
            name='clase_origen',
            field=models.ForeignKey(blank=True, help_text='Clase en la que se realizó la venta (Sede + Horario + Profe).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_clase', to='core.claseprogramada'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_comision_asistente',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Comisión para el profesor asistente de la clase origen.', max_digits=10, verbose_name='Monto Comisión Asistente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='monto_costo_reposicion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Suma de los costos de los items vendidos.', max_digits=10, verbose_name='Monto Costo Reposición'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='utilidad_neta_asociacion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que queda en caja tras costos y comisiones.', max_digits=10, verbose_name='Utilidad Neta Asociación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_reposicion',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que le cuesta a la asociación reponer este producto.', max_digits=10, verbose_name='Costo de Reposición'),
        ),
    ]
