# Generated by Django 5.2.5 on 2026-04-01 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_claseprogramada_porcentaje_comision_asistente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar la jerarquía (ej. 0=Blanco, 1=Final)')),
            ],
            options={
                'verbose_name': 'Grado / Faja',
                'verbose_name_plural': 'Grados / Fajas',
                'ordering': ['orden'],
            },
        ),
        migrations.AlterField(
            model_name='documento',
            name='nivel_acceso',
            field=models.CharField(choices=[('todos', 'Público / Todos los Alumnos'), ('principiantes', 'Principiantes y superior'), ('intermedios', 'Intermedios y superior'), ('avanzados', 'Avanzados y superior'), ('superior', 'Nivel Superior'), ('maestros', 'Maestros')], default='todos', max_length=20),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='nivel_acceso',
            field=models.CharField(choices=[('todos', 'Público / Todos los Alumnos'), ('principiantes', 'Principiantes y superior'), ('intermedios', 'Intermedios y superior'), ('avanzados', 'Avanzados y superior'), ('superior', 'Nivel Superior'), ('maestros', 'Maestros')], default='todos', max_length=20),
        ),
        migrations.AlterField(
            model_name='examen',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes_obtenidos', to='core.grado'),
        ),
    ]
