# Generated by Django 5.2.5 on 2026-04-01 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_grado_alter_documento_nivel_acceso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='nivel_desbloqueado',
            field=models.CharField(choices=[('todos', 'Público / Todos los Alumnos'), ('principiantes', 'Principiantes y superior'), ('intermedios', 'Intermedios y superior'), ('avanzados', 'Avanzados y superior'), ('superior', 'Nivel Superior'), ('maestros', 'Maestros')], default='principiantes', help_text='Al obtener este grado en un examen, el alumno desbloquea este nivel de contenido en la academia.', max_length=20, verbose_name='Nivel de Acceso que Otorga'),
        ),
    ]
