# Generated by Django 5.2.5 on 2026-04-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_grado_nivel_desbloqueado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='core.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto (Talle)',
                'verbose_name_plural': 'Variantes de Producto (Talles)',
            },
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='variante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.productovariante'),
        ),
    ]
