# Generated by Django 5.2.5 on 2026-04-02 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_producto_stock_productovariante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('mapa_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Maps')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': '01 - Sedes',
                'ordering': ['nombre'],
            },
        ),
        migrations.RemoveField(
            model_name='claseprogramada',
            name='actividad',
        ),
        migrations.RemoveField(
            model_name='claseprogramada',
            name='horarios',
        ),
        migrations.RemoveField(
            model_name='claseprogramada',
            name='locacion',
        ),
        migrations.RemoveField(
            model_name='claseprogramada',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='claseprogramada',
            name='profesor_asistente',
        ),
        migrations.RemoveField(
            model_name='locacion',
            name='actividades',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='locacion',
        ),
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': '02 - Actividades'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Asistencia', 'verbose_name_plural': '04 - Registro de Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='categoriacontenido',
            options={'ordering': ['nombre'], 'verbose_name': 'Academia: Categoría', 'verbose_name_plural': '12 - Academia: Categorías'},
        ),
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto: Categoría', 'verbose_name_plural': '09 - Tienda: Categorías'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Academia: Documento', 'verbose_name_plural': '13 - Academia: Documentos'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-fecha'], 'verbose_name': 'Examen / Graduación', 'verbose_name_plural': '06 - Exámenes y Graduaciones'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['orden'], 'verbose_name': 'Escala de Grados', 'verbose_name_plural': '05 - Escala de Grados / Fajas'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Pago / Finanzas', 'verbose_name_plural': '08 - Pagos y Tesorería'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Tienda: Pedido', 'verbose_name_plural': '11 - Tienda: Gestión de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto: Ficha Central', 'verbose_name_plural': '10 - Tienda: Productos'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Usuario / Alumno / Profe', 'verbose_name_plural': '03 - Usuarios (Panel Maestro)'},
        ),
        migrations.AlterModelOptions(
            name='videotutorial',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Academia: Video', 'verbose_name_plural': '14 - Academia: Videos Tutoriales'},
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], default='LU', max_length=2, verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('porcentaje_comision_asistente', models.DecimalField(decimal_places=2, default=0, help_text='Comisión que se lleva el asistente por las ventas registradas en esta clase.', max_digits=5, verbose_name=' % Comisión Asistente')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='core.actividad')),
                ('profesor', models.ForeignKey(limit_choices_to={'es_profe': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL)),
                ('profesor_asistente', models.ForeignKey(blank=True, limit_choices_to={'es_profe': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_asistente', to=settings.AUTH_USER_MODEL)),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='core.sede')),
            ],
            options={
                'verbose_name': 'Horario / Clase',
                'verbose_name_plural': '07 - Cronograma de Clases',
                'ordering': ['sede', 'dia', 'hora_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='pago',
            name='clase_programada',
            field=models.ForeignKey(blank=True, help_text='Clase específica a la cual pertenece este pago (Sede + Actividad + Horario).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='core.cronograma'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='clase_origen',
            field=models.ForeignKey(blank=True, help_text='Clase en la que se realizó la venta (Sede + Horario + Profe).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_clase', to='core.cronograma'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='core.sede'),
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Locacion',
        ),
        migrations.DeleteModel(
            name='ClaseProgramada',
        ),
    ]
