# Generated by Django 5.2.5 on 2026-04-02 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sede_remove_claseprogramada_actividad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actividad',
            options={'verbose_name': 'Actividad', 'verbose_name_plural': '01.2 - Actividades'},
        ),
        migrations.AlterModelOptions(
            name='asistencia',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Asistencia', 'verbose_name_plural': '02.2 - Registro de Asistencias'},
        ),
        migrations.AlterModelOptions(
            name='categoriacontenido',
            options={'ordering': ['nombre'], 'verbose_name': 'Academia: Categoría', 'verbose_name_plural': '05.1 - Academia: Materias Digitales'},
        ),
        migrations.AlterModelOptions(
            name='categoriaproducto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto: Categoría', 'verbose_name_plural': '04.2 - Tienda: Categorías (Configuración)'},
        ),
        migrations.AlterModelOptions(
            name='cronograma',
            options={'ordering': ['sede', 'dia', 'hora_inicio'], 'verbose_name': 'Horario / Clase', 'verbose_name_plural': '01.3 - Cronograma de Clases'},
        ),
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Academia: Documento', 'verbose_name_plural': '05.2 - Academia: Documentos (Oculto)'},
        ),
        migrations.AlterModelOptions(
            name='examen',
            options={'ordering': ['-fecha'], 'verbose_name': 'Examen / Graduación', 'verbose_name_plural': '03.2 - Exámenes y Graduaciones'},
        ),
        migrations.AlterModelOptions(
            name='grado',
            options={'ordering': ['orden'], 'verbose_name': 'Escala de Grados', 'verbose_name_plural': '03.1 - Escala de Grados / Fajas'},
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Pago / Finanzas', 'verbose_name_plural': '02.3 - Pagos y Tesorería'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Tienda: Pedido', 'verbose_name_plural': '04.3 - Tienda: Gestión de Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto: Ficha Central', 'verbose_name_plural': '04.1 - Tienda: Productos'},
        ),
        migrations.AlterModelOptions(
            name='sede',
            options={'ordering': ['nombre'], 'verbose_name': 'Sede', 'verbose_name_plural': '01.1 - Sedes'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['apellido', 'nombre'], 'verbose_name': 'Usuario / Alumno / Profe', 'verbose_name_plural': '02.1 - Panel Maestro de Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='videotutorial',
            options={'ordering': ['-fecha_subida'], 'verbose_name': 'Academia: Video', 'verbose_name_plural': '05.3 - Academia: Videos (Oculto)'},
        ),
        migrations.AlterField(
            model_name='documento',
            name='nivel_acceso',
            field=models.CharField(choices=[('alumno', 'Alumnos (Todos)'), ('principiante', 'Principiantes'), ('avanzado', 'Avanzados'), ('instructor', 'Instructores'), ('profesor', 'Profesores'), ('maestro', 'Maestros')], default='alumno', max_length=20),
        ),
        migrations.AlterField(
            model_name='grado',
            name='nivel_desbloqueado',
            field=models.CharField(choices=[('alumno', 'Alumnos (Todos)'), ('principiante', 'Principiantes'), ('avanzado', 'Avanzados'), ('instructor', 'Instructores'), ('profesor', 'Profesores'), ('maestro', 'Maestros')], default='principiante', help_text='Al obtener este grado en un examen, el alumno desbloquea este nivel de contenido en la academia.', max_length=20, verbose_name='Nivel de Acceso que Otorga'),
        ),
        migrations.AlterField(
            model_name='videotutorial',
            name='nivel_acceso',
            field=models.CharField(choices=[('alumno', 'Alumnos (Todos)'), ('principiante', 'Principiantes'), ('avanzado', 'Avanzados'), ('instructor', 'Instructores'), ('profesor', 'Profesores'), ('maestro', 'Maestros')], default='alumno', max_length=20),
        ),
    ]
