# Generated by Django 5.2.5 on 2026-04-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_actividad_options_alter_asistencia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='examinador_externo',
            field=models.CharField(blank=True, max_length=150, verbose_name='Maestro Invitado (si no está en la app)'),
        ),
    ]
