# Generated by Django 5.2.5 on 2026-04-03 00:05

from django.db import migrations


def migrate_nivel_acceso(apps, schema_editor):
    Grado = apps.get_model('core', 'Grado')
    Documento = apps.get_model('core', 'Documento')
    VideoTutorial = apps.get_model('core', 'VideoTutorial')
    
    mapping = {
        'todos': 'alumno',
        'principiantes': 'principiante',
        'intermedios': 'avanzado',
        'avanzados': 'instructor',
        'superior': 'profesor',
        'maestros': 'maestro'
    }
    
    for old, new in mapping.items():
        Grado.objects.filter(nivel_desbloqueado=old).update(nivel_desbloqueado=new)
        Documento.objects.filter(nivel_acceso=old).update(nivel_acceso=new)
        VideoTutorial.objects.filter(nivel_acceso=old).update(nivel_acceso=new)

def reverse_migrate_nivel_acceso(apps, schema_editor):
    Grado = apps.get_model('core', 'Grado')
    Documento = apps.get_model('core', 'Documento')
    VideoTutorial = apps.get_model('core', 'VideoTutorial')
    
    mapping = {
        'alumno': 'todos',
        'principiante': 'principiantes',
        'avanzado': 'intermedios',
        'instructor': 'avanzados',
        'profesor': 'superior',
        'maestro': 'maestros'
    }
    
    for old, new in mapping.items():
        Grado.objects.filter(nivel_desbloqueado=old).update(nivel_desbloqueado=new)
        Documento.objects.filter(nivel_acceso=old).update(nivel_acceso=new)
        VideoTutorial.objects.filter(nivel_acceso=old).update(nivel_acceso=new)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_examen_examinador_externo'),
    ]

    operations = [
        migrations.RunPython(migrate_nivel_acceso, reverse_migrate_nivel_acceso),
    ]
