# Generated by Django 5.2.5 on 2026-04-03 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20260402_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='core.grado', verbose_name='Grado / Faja Actual'),
        ),
    ]
