# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_mes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Mensual')),
                ('precio_clase', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Clase Suelta')),
            ],
            options={
                'verbose_name': 'Actividad',
                'verbose_name_plural': '01.2 - Actividades',
                'db_table': 'core_actividad',
            },
        ),
        migrations.CreateModel(
            name='InscripcionClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('regular', 'Inscrito (Confirmado)'), ('espera', 'En Lista de Espera'), ('baja', 'Dado de Baja')], default='regular', max_length=20)),
            ],
            options={
                'verbose_name': 'Inscripción a Clase',
                'verbose_name_plural': '01.4 - Inscripciones (Control de Cupo)',
                'db_table': 'core_inscripcionclase',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('mapa_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace Google Maps')),
            ],
            options={
                'verbose_name': 'Sede',
                'verbose_name_plural': '01.1 - Sedes',
                'db_table': 'core_sede',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado'), ('DO', 'Domingo')], default='LU', max_length=2, verbose_name='Día de la semana')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Fin')),
                ('cupo', models.PositiveIntegerField(default=20, help_text='Cantidad máxima de alumnos permitidos en este horario.', verbose_name='Cupo Máximo')),
                ('porcentaje_comision_asistente', models.DecimalField(decimal_places=2, default=0, help_text='Comisión que se lleva el asistente por las ventas registradas en esta clase.', max_digits=5, verbose_name=' % Comisión Asistente')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='academia.actividad')),
            ],
            options={
                'verbose_name': 'Horario / Clase',
                'verbose_name_plural': '01.3 - Cronograma de Clases',
                'db_table': 'core_cronograma',
                'ordering': ['sede', 'dia', 'hora_inicio'],
            },
        ),
    ]
