# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='profesor',
            field=models.ForeignKey(limit_choices_to={'es_profe': True}, on_delete=django.db.models.deletion.CASCADE, related_name='clases_dictadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='profesor_asistente',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_profe': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clases_asistente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionclase',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_academia', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionclase',
            name='clase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_inscritos', to='academia.cronograma'),
        ),
        migrations.AddField(
            model_name='cronograma',
            name='sede',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clases_asignadas', to='academia.sede'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionclase',
            unique_together={('alumno', 'clase')},
        ),
    ]
