# Generated by Django 5.2.5 on 2026-04-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='color_etiqueta',
            field=models.CharField(default='#f97316', help_text='Color para diferenciar la actividad en el cronograma. (Ej: #3b82f6)', max_length=7, verbose_name='Color Hex'),
        ),
    ]
