# Generated by Django 5.2.5 on 2026-04-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0003_actividad_color_etiqueta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cronograma',
            name='dia',
            field=models.CharField(choices=[('LU', 'Lunes'), ('MA', 'Martes'), ('MI', 'Miércoles'), ('JU', 'Jueves'), ('VI', 'Viernes'), ('SA', 'Sábado')], default='LU', max_length=2, verbose_name='Día de la semana'),
        ),
    ]
