# Generated by Django 5.1.2 on 2026-04-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0004_alter_cronograma_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronograma',
            name='porcentaje_comision_profesor',
            field=models.DecimalField(decimal_places=2, default=50, help_text='Porcentaje de la cuota o clase que se lleva el profesor principal.', max_digits=5, verbose_name=' % Comisión Profesor'),
        ),
    ]
