# Generated by Django 5.1.2 on 2026-05-15 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0005_cronograma_porcentaje_comision_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='tipo_cobro',
            field=models.CharField(choices=[('mes', 'Mes Completo'), ('clase', 'Clase Suelta'), ('paquete', 'Paquete de Clases')], default='mes', max_length=20, verbose_name='Tipo de Cobro'),
        ),
    ]
