# Generated by Django 5.1.2 on 2026-05-24 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0006_actividad_tipo_cobro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('lugar', models.CharField(max_length=200)),
                ('costo_inscripcion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Inscripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Convocatoria Abierta')),
            ],
            options={
                'verbose_name': 'Torneo',
                'verbose_name_plural': '01.5 - Torneos',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inscripcion', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones_torneos', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_inscritos', to='academia.torneo')),
            ],
            options={
                'verbose_name': 'Inscripción a Torneo',
                'verbose_name_plural': '01.6 - Inscripciones a Torneos',
                'unique_together': {('alumno', 'torneo')},
            },
        ),
    ]
