# Generated by Django 5.1.2 on 2026-05-24 22:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academia', '0007_torneo_inscripciontorneo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(help_text='Ej: Formas de Puño, Combate, Armas...', max_length=100, verbose_name='Categoría')),
                ('asistio', models.BooleanField(default=True, verbose_name='¿Asistió?')),
                ('podio', models.CharField(choices=[('ninguno', 'Participación (Sin Podio)'), ('1ro', '1er Puesto 🥇'), ('2do', '2do Puesto 🥈'), ('3ro', '3er Puesto 🥉'), ('mencion', 'Mención Especial 🏅')], default='ninguno', max_length=20, verbose_name='Podio / Resultado')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_torneos', to=settings.AUTH_USER_MODEL)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_alumnos', to='academia.torneo')),
            ],
            options={
                'verbose_name': 'Resultado de Torneo',
                'verbose_name_plural': '01.7 - Resultados de Torneos',
                'unique_together': {('alumno', 'torneo', 'categoria')},
            },
        ),
    ]
