"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Carga las variables de entorno del archivo .env localizado en la raíz del proyecto
load_dotenv()

def get_env(name, default=None, required=False):
    """Obtiene una variable de entorno. Lanza error si es requerida y no existe."""
    value = os.getenv(name, default)
    if required and not value:
        raise ImproperlyConfigured(
            f"❌ Variable de entorno requerida no definida: '{name}'. "
            f"Agregala a tu archivo .env o a las variables secretas de Render."
        )
    return value

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# La clave DEBE estar definida en las variables de entorno (Render Secrets / .env local).
# Si no está definida, el servidor NO arrancará.
SECRET_KEY = get_env("SECRET_KEY", required=True)

# SECURITY WARNING: don't run with debug turned on in production!
# En producción, definir DEBUG=False en las variables de entorno.
# El default seguro es False — nunca True en producción.
DEBUG = get_env("DEBUG", default="False") == "True"

ALLOWED_HOSTS = get_env("ALLOWED_HOSTS", default="localhost,127.0.0.1,.onrender.com").split(",")

# CSRF Trusted Origins para producción
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
    "https://longhuhe.onrender.com",
]

# Configuración para que Django reconozca HTTPS detrás del Proxy de Render
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Configuraciones de seguridad — solo activas en producción (DEBUG=False)
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.usuarios',
    'apps.academia',
    'apps.asistencia',
    'apps.ventas',
    'apps.biblioteca',
    'apps.examenes',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'apps.usuarios.context_processors.alumno_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuración de Base de Datos: PRIORIDAD REMOTA si existe el URL
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    DATABASES = {
        "default": dj_database_url.config(
            default=DATABASE_URL,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Fallback local para desarrollo (SQLite) sino hay DATABASE_URL
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-ar'

TIME_ZONE = 'America/Argentina/Buenos_Aires'

USE_I18N = True

USE_TZ = True


# Custom user model
AUTH_USER_MODEL = "usuarios.Usuario"


# Configuración Mercado Pago
MP_ACCESS_TOKEN = os.getenv("MP_ACCESS_TOKEN", "")
MP_WEBHOOK_SECRET = os.getenv("MP_WEBHOOK_SECRET", "") # Para validación X-Signature

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# --- CONFIGURACIÓN DE ALMACENAMIENTO (SUPABASE STORAGE) ---
USE_S3_VARS = {
    'AWS_ACCESS_KEY_ID': os.getenv('AWS_ACCESS_KEY_ID'),
    'AWS_SECRET_ACCESS_KEY': os.getenv('AWS_SECRET_ACCESS_KEY'),
    'AWS_STORAGE_BUCKET_NAME': os.getenv('AWS_STORAGE_BUCKET_NAME'),
    'AWS_S3_ENDPOINT_URL': os.getenv('AWS_S3_ENDPOINT_URL')
}
USE_S3 = all(USE_S3_VARS.values())

print("--- DIAGNÓSTICO S3 STARTUP ---")
print(f"Estado USE_S3: {USE_S3}")
if not USE_S3:
    missing = [k for k, v in USE_S3_VARS.items() if not v]
    print(f"Variables faltantes o vacías: {missing}")
print("------------------------------")

MEDIA_ROOT = BASE_DIR / "media"

if USE_S3:
    STORAGES = {
        "default": {
            "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
            "OPTIONS": {
                "access_key": os.getenv('AWS_ACCESS_KEY_ID'),
                "secret_key": os.getenv('AWS_SECRET_ACCESS_KEY'),
                "bucket_name": os.getenv('AWS_STORAGE_BUCKET_NAME'),
                "endpoint_url": os.getenv('AWS_S3_ENDPOINT_URL'),
                "region_name": "sa-east-1",
                "signature_version": "s3v4",
                "addressing_style": "path",
                "file_overwrite": False,
                "default_acl": None,
                "querystring_auth": True, # Activamos firmas para buckets privados
            }
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    
    # Test de conexión S3 en el arranque
    try:
        from storages.backends.s3boto3 import S3Boto3Storage
        test_storage = S3Boto3Storage(
            access_key=os.getenv('AWS_ACCESS_KEY_ID'),
            secret_key=os.getenv('AWS_SECRET_ACCESS_KEY'),
            bucket_name=os.getenv('AWS_STORAGE_BUCKET_NAME'),
            endpoint_url=os.getenv('AWS_S3_ENDPOINT_URL'),
            region_name="sa-east-1"
        )
        test_storage.exists('test_connection.txt')
        print("--- S3 CONNECTION TEST: SUCCESS ---")
    except Exception as e:
        print(f"--- S3 CONNECTION TEST: FAILED - {str(e)} ---")
    
    AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.getenv('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_ENDPOINT_URL = os.getenv('AWS_S3_ENDPOINT_URL')
    AWS_S3_REGION_NAME = 'sa-east-1' # Fijamos la región para evitar errores de firma
    
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    AWS_S3_VERIFY = True
    AWS_QUERYSTRING_AUTH = True # Importante para buckets privados
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_S3_ADDRESSING_STYLE = "path"
    
    SUPABASE_PID = os.getenv('SUPABASE_PROJECT_ID', 'pzikczglcocxhosdpinw')
    # Ya no construimos MEDIA_URL manualmente; dejamos que django-storages genere URLs firmadas.
    MEDIA_URL = None
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    MEDIA_URL = "/media/"

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
STATIC_ROOT = BASE_DIR / "staticfiles"
