# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveIntegerField(default=0, help_text='Para ordenar la jerarquía (ej. 0=Blanco, 1=Final)')),
                ('nivel_desbloqueado', models.CharField(choices=[('alumno', 'Alumnos (Todos)'), ('principiante', 'Principiantes'), ('avanzado', 'Avanzados'), ('instructor', 'Instructores'), ('profesor', 'Profesores'), ('maestro', 'Maestros')], default='principiante', help_text='Al obtener este grado en un examen, el alumno desbloquea este nivel de contenido en la academia.', max_length=20, verbose_name='Nivel de Acceso que Otorga')),
            ],
            options={
                'verbose_name': 'Escala de Grados',
                'verbose_name_plural': '03.1 - Escala de Grados / Fajas',
                'db_table': 'core_grado',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('celular', models.CharField(max_length=30, unique=True)),
                ('es_profe', models.BooleanField(default=False)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/', verbose_name='Foto de Perfil')),
                ('mp_access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='MP Access Token')),
                ('mp_public_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='MP Public Key')),
                ('dni', models.CharField(blank=True, max_length=15, verbose_name='DNI')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('domicilio', models.CharField(blank=True, max_length=255, verbose_name='Domicilio')),
                ('localidad', models.CharField(blank=True, max_length=150, verbose_name='Localidad')),
                ('fecha_ingreso_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso a la Asociación')),
                ('alergias', models.TextField(blank=True, verbose_name='Alergias Conocidas')),
                ('condiciones_medicas', models.TextField(blank=True, verbose_name='Condiciones Médicas')),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=120, verbose_name='Nombre Contacto Emergencia')),
                ('contacto_emergencia_telefono', models.CharField(blank=True, max_length=50, verbose_name='Teléfono Contacto Emergencia')),
                ('apto_medico', models.FileField(blank=True, null=True, upload_to='aptos_medicos/', verbose_name='Certificado Apto Médico')),
                ('uuid_carnet', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('fecha_vencimiento_cuota', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento de Cuota')),
                ('rol_acceso_total', models.BooleanField(default=False, help_text='Control absoluto sobre toda la plataforma (Dios).', verbose_name='Acceso Total (Superadministrador)')),
                ('rol_gestion_alumnos', models.BooleanField(default=False, help_text='Inscripciones, morosidad, aptos médicos.', verbose_name='Gestión de Alumnos')),
                ('rol_gestion_sedes', models.BooleanField(default=False, help_text='Locaciones, clases, horarios, exámenes.', verbose_name='Gestión de Sedes')),
                ('rol_gestion_tienda', models.BooleanField(default=False, help_text='Productos, stock, pedidos.', verbose_name='Gestión de Tienda')),
                ('rol_gestion_tesoreria', models.BooleanField(default=False, help_text='Todo el dinero de la asociación.', verbose_name='Gestión de Tesorería (Global)')),
                ('rol_gestion_academia', models.BooleanField(default=False, help_text='Biblioteca de videos y documentos.', verbose_name='Gestión de Academia')),
                ('autorizacion_tesoreria_activa', models.BooleanField(default=False, help_text='Interruptor de seguridad. Si es falso, el delegado no podrá entrar al panel de tesorería.', verbose_name='Autorización Tesorería Activa')),
                ('actividades', models.ManyToManyField(blank=True, related_name='alumnos', to='academia.actividad')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('sede', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='academia.sede')),
                ('tesorero_autorizado', models.ForeignKey(blank=True, help_text='Persona que gestionará las comisiones de este profesor.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesoreria_admin_de', to=settings.AUTH_USER_MODEL, verbose_name='Tesorero Autorizado (Delegado)')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('grado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alumnos', to='usuarios.grado', verbose_name='Grado / Faja Actual')),
            ],
            options={
                'db_table': 'core_usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha del Examen')),
                ('examinador_externo', models.CharField(blank=True, max_length=150, verbose_name='Maestro Invitado (si no está en la app)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones / Detalles')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to=settings.AUTH_USER_MODEL)),
                ('examinador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes_tomados', to=settings.AUTH_USER_MODEL)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes_obtenidos', to='usuarios.grado')),
            ],
            options={
                'verbose_name': 'Examen / Graduación',
                'verbose_name_plural': '03.2 - Exámenes y Graduaciones',
                'db_table': 'core_examen',
                'ordering': ['-fecha'],
            },
        ),
    ]
