# Generated by Django 5.2.5 on 2026-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='examinador_externo',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Maestro Invitado (si no está en la app)'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='alergias',
            field=models.TextField(blank=True, default='', verbose_name='Alergias Conocidas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='condiciones_medicas',
            field=models.TextField(blank=True, default='', verbose_name='Condiciones Médicas'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contacto_emergencia_nombre',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Nombre Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='contacto_emergencia_telefono',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Teléfono Contacto Emergencia'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mp_access_token',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MP Access Token'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='mp_public_key',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='MP Public Key'),
        ),
    ]
