# Generated by Django 5.2.5 on 2026-04-06 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_examen_examinador_externo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clases_disponibles',
            field=models.PositiveIntegerField(default=0, verbose_name='Clases Disponibles (Paquetes)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='contacto_emergencia_direccion',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Dirección Contacto Emergencia'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_prorroga',
            field=models.DateField(blank=True, help_text='Si solicita prórroga, tiene acceso hasta esta fecha.', null=True, verbose_name='Vencimiento de Prórroga'),
        ),
    ]
