# Generated by Django 5.2.5 on 2026-04-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_usuario_clases_disponibles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='qr_base64_cache',
            field=models.TextField(blank=True, help_text='Caché del código QR en base64 para evitar regenerarlo en memoria repetidamente.', null=True),
        ),
    ]
