# Generated by Django 5.1.2 on 2026-04-16 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_usuario_qr_base64_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_becado',
            field=models.BooleanField(default=False, help_text='Si está activo, el alumno tiene exención total de cuota. No necesita registrar pagos mensuales.', verbose_name='Es Becado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='motivo_beca',
            field=models.CharField(blank=True, default='', help_text='Ej: Hijo del instructor, Situación económica, Beca de rendimiento.', max_length=255, verbose_name='Motivo de Beca'),
        ),
    ]
