# Generated by Django 5.1.2 on 2026-04-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_becas_y_descuentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='dia_corte_cuota',
            field=models.PositiveSmallIntegerField(default=0, help_text='Día del mes en que vence la cuota del alumno (Ej: 5 = vence el día 5 de cada mes). 0 = se usa el día actual del primer pago. Se asigna automáticamente al aprobar el primer pago.', verbose_name='Día de Corte de Cuota'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fecha_prorroga',
            field=models.DateField(blank=True, help_text='Si solicita prórroga, tiene acceso de asistencia hasta esta fecha. Solo 1 por período de cuota.', null=True, verbose_name='Vencimiento de Prórroga'),
        ),
    ]
