# Generated by Django 5.1.2 on 2026-04-17 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_usuario_dia_corte_cuota_alter_usuario_fecha_prorroga'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='ultima_prorroga_solicitada',
            field=models.DateField(blank=True, help_text='Fecha en que se solicitó la última prórroga. Se usa para limitar a una por mes.', null=True, verbose_name='Última Prórroga Solicitada'),
        ),
    ]
