# Generated by Django 5.1.2 on 2026-04-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_usuario_ultima_prorroga_solicitada'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nivel_acceso',
            field=models.CharField(choices=[('alumno', 'Alumnos (Todos)'), ('principiante', 'Principiantes'), ('avanzado', 'Avanzados'), ('instructor', 'Instructores'), ('profesor', 'Profesores'), ('maestro', 'Maestros')], default='alumno', help_text='Determina qué contenido de la biblioteca puede ver el alumno.', max_length=20, verbose_name='Nivel de Acceso Academia'),
        ),
    ]
