# Generated by Django 5.1.2 on 2026-04-17 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_usuario_nivel_acceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='qr_image',
            field=models.ImageField(blank=True, null=True, upload_to='qrs/', verbose_name='Código QR'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='qr_base64_cache',
            field=models.TextField(blank=True, help_text='[DEPRECATED] Usar qr_image en su lugar.', null=True),
        ),
    ]
