# Generated by Django 5.1.2 on 2026-04-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_asegurar_superusuario_lucas'),
    ]

    operations = [
        migrations.AddField(
            model_name='grado',
            name='costo_examen',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Examen'),
        ),
    ]
