# Generated by Django 5.1.2 on 2026-05-15 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_grado_costo_examen'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraSeguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('login_ok', 'Acceso Exitoso'), ('login_fail', 'Acceso Fallido'), ('cambio_estado', 'Cambio de Estado Financiero'), ('cierre_caja', 'Cierre de Caja'), ('exportacion', 'Exportación de Datos'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bitácora de Seguridad',
                'verbose_name_plural': 'Bitácoras de Seguridad',
                'ordering': ['-fecha'],
            },
        ),
    ]
