# Generated by Django 5.1.2 on 2026-05-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_bitacoraseguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha del Examen'),
        ),
    ]
