# Generated by Django 5.1.2 on 2026-05-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_examen_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='pin_hash',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='PIN de Acceso Hasheado'),
        ),
    ]
