# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Producto: Categoría',
                'verbose_name_plural': '04.2 - Tienda: Categorías (Configuración)',
                'db_table': 'core_categoriaproducto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_comision_profesor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_utilidad_asociacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('fecha_pago_real', models.DateField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('mes', 'Mes Completo'), ('clase_suelta', '1 Clase'), ('paquete', 'Paquete de Clases')], max_length=20)),
                ('cantidad_clases', models.IntegerField(blank=True, null=True)),
                ('metodo', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('mercadopago', 'Mercado Pago'), ('efectivo', 'En Efectivo')], max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pendiente', max_length=20)),
                ('mercado_pago_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_status', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='academia.actividad')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to=settings.AUTH_USER_MODEL)),
                ('clase_programada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='academia.cronograma')),
            ],
            options={
                'verbose_name': 'Pago / Finanzas',
                'verbose_name_plural': '02.3 - Pagos y Tesorería',
                'db_table': 'core_pago',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Pago/Conf'), ('pagado', 'Pagado - A Preparar'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('mercadopago', 'Mercado Pago'), ('efectivo', 'En Efectivo')], max_length=20)),
                ('cuotas', models.IntegerField(default=1)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes_pedidos/')),
                ('mercado_pago_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mercado_pago_status', models.CharField(blank=True, max_length=50, null=True)),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_comision', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_costo_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_comision_asistente', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('utilidad_neta_asociacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('backorder', models.BooleanField(default=False)),
                ('stock_descontado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_tienda', to=settings.AUTH_USER_MODEL)),
                ('clase_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_clase', to='academia.cronograma')),
                ('profesor_venta', models.ForeignKey(blank=True, limit_choices_to={'es_profe': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_tienda_generadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tienda: Pedido',
                'verbose_name_plural': '04.3 - Tienda: Gestión de Pedidos',
                'db_table': 'core_pedido',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('permite_backorder', models.BooleanField(default=False)),
                ('cuotas_maximas', models.IntegerField(default=1, verbose_name='Cuotas Máximas')),
                ('costo_reposicion', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Reposición')),
                ('porcentaje_comision', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje de Comisión Profe')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock Global (si no hay variantes)')),
                ('foto1', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto2', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto3', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto4', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('foto5', models.ImageField(blank=True, null=True, upload_to='tienda/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='ventas.categoriaproducto')),
            ],
            options={
                'verbose_name': 'Producto: Ficha Central',
                'verbose_name_plural': '04.1 - Tienda: Productos',
                'db_table': 'core_producto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProductoVariante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talle', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad en Stock')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='ventas.producto')),
            ],
            options={
                'verbose_name': 'Variante de Producto (Talle)',
                'verbose_name_plural': 'Variantes de Producto (Talles)',
                'db_table': 'core_productovariante',
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ventas.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ventas.producto')),
                ('variante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.productovariante')),
            ],
            options={
                'verbose_name': 'Item de Pedido',
                'verbose_name_plural': 'Items de Pedido',
                'db_table': 'core_pedidoitem',
            },
        ),
    ]
