# Generated by Django 5.1.2 on 2026-04-16 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Nombre descriptivo, ej: 'Descuento Hermanos 20%' o 'Beca Parcial Familia García'.", max_length=150)),
                ('descripcion', models.TextField(blank=True, default='', help_text='Razón del descuento, condiciones, etc.', verbose_name='Descripción / Nota Interna')),
                ('tipo', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('monto_fijo', 'Monto Fijo ($)')], default='porcentaje', max_length=20, verbose_name='Tipo de Descuento')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Si es porcentaje: ingresá 20 para 20%. Si es monto fijo: ingresá 1500 para $1.500.', max_digits=10, verbose_name='Valor del Descuento')),
                ('codigo', models.CharField(blank=True, default='', help_text='Opcional. Si se completa, el descuento sólo se aplica cuando se ingresa este código. Ej: HERMANOS, FAMILIA2025.', max_length=50, verbose_name='Código de Cupón')),
                ('activo', models.BooleanField(default=True, help_text='Desactiválo temporalmente sin borrar el historial.')),
                ('usos_maximos', models.PositiveIntegerField(blank=True, help_text='Dejá vacío para usos ilimitados.', null=True, verbose_name='Máximo de Usos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, editable=False, verbose_name='Usos Actuales')),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Dejá vacío si no vence nunca.', null=True, verbose_name='Fecha de Vencimiento')),
                ('aplicable_a', models.CharField(choices=[('todos', 'Todos los tipos de pago'), ('cuota_mensual', 'Solo Cuota Mensual'), ('clase_suelta', 'Solo Clase Suelta'), ('paquete', 'Solo Paquete de Clases')], default='todos', max_length=20, verbose_name='Aplicable a')),
            ],
            options={
                'verbose_name': 'Descuento / Cupón',
                'verbose_name_plural': '02.4 - Descuentos y Cupones',
                'db_table': 'core_descuento',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calculado automáticamente al guardar según el descuento seleccionado.', max_digits=10, verbose_name='Monto Descontado'),
        ),
        migrations.AddField(
            model_name='pago',
            name='descuento',
            field=models.ForeignKey(blank=True, help_text='Cuponetera o descuento aplicado a este pago.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_con_descuento', to='ventas.descuento', verbose_name='Descuento Aplicado'),
        ),
    ]
