# Generated by Django 5.1.2 on 2026-04-17 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_becas_y_descuentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='monto_original',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio base antes de aplicar cualquier descuento. Referencia inmutable.', max_digits=10, verbose_name='Monto Original (sin descuento)'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='descuento',
            field=models.ForeignKey(blank=True, help_text='Solo válido para pagos de tipo Mes Completo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_con_descuento', to='ventas.descuento', verbose_name='Descuento Aplicado'),
        ),
    ]
