# Generated by Django 5.1.2 on 2026-04-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_pago_monto_original_alter_pago_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='monto_reserva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo para encargar el producto si no se paga el total.', max_digits=10, verbose_name='Monto de Reserva (Seña)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de Pago/Conf'), ('pagado', 'Pagado - A Preparar'), ('reservado', 'Reservado / Señado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
