# Generated by Django 5.1.2 on 2026-04-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0004_producto_monto_reserva_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='descuento',
            name='monto_maximo_descuento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para descuentos porcentuales, este es el monto máximo que se restará (ej: 50% con tope de $1.000).', max_digits=10, null=True, verbose_name='Tope Máximo de Descuento'),
        ),
        migrations.AddField(
            model_name='descuento',
            name='monto_minimo_pago',
            field=models.DecimalField(decimal_places=2, default=0, help_text='El cupón solo será aplicable si el total es igual o superior a este monto.', max_digits=10, verbose_name='Monto Mínimo de Pago'),
        ),
        migrations.AddConstraint(
            model_name='descuento',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('codigo',), name='unique_active_discount_code'),
        ),
    ]
