# Generated by Django 5.1.2 on 2026-04-17 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_descuento_monto_maximo_descuento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Opcional. Si se completa, el descuento sólo se aplica cuando se ingresa este código. Ej: HERMANOS, FAMILIA2025.', max_length=50, verbose_name='Código de Cupón'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_tienda', to=settings.AUTH_USER_MODEL),
        ),
    ]
