# Generated by Django 5.1.2 on 2026-04-20 11:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_descuento_codigo_alter_pago_alumno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('mes', 'Mes Completo'), ('clase_suelta', '1 Clase'), ('paquete', 'Paquete de Clases'), ('examen', 'Derecho de Examen')], max_length=20),
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField()),
                ('anio', models.PositiveIntegerField()),
                ('total_recaudado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='cierres_caja/')),
                ('usuario_genero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cierre de Caja',
                'verbose_name_plural': '04.5 - Historial de Cierres de Caja',
                'ordering': ['-anio', '-mes'],
            },
        ),
    ]
