# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaContenido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('icono', models.CharField(default='book', help_text='Slug de icono Lucide/Heroicon', max_length=50)),
                ('orden', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Biblioteca: Categoría',
                'verbose_name_plural': '05.1 - Biblioteca: Categorías',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='VisualizacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('veces', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Biblioteca: Registro de Vista',
                'verbose_name_plural': '05.3 - Biblioteca: Tracking de Vistas',
            },
        ),
        migrations.CreateModel(
            name='MaterialEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('pdf', 'Documento PDF'), ('video', 'URL de Video (YouTube/Vimeo)'), ('teoria', 'Texto / Teoría')], default='pdf', max_length=20)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='biblioteca/')),
                ('video_url', models.URLField(blank=True, help_text='Pega el link de YouTube', null=True)),
                ('contenido_teorico', models.TextField(blank=True, help_text='Para material de teoría directa (Texto/HTML)')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='biblioteca.categoriacontenido')),
            ],
            options={
                'verbose_name': 'Biblioteca: Material',
                'verbose_name_plural': '05.2 - Biblioteca: Materiales',
                'ordering': ['grado_minimo__orden', 'titulo'],
            },
        ),
    ]
