# Generated by Django 5.2.5 on 2026-04-04 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialestudio',
            name='grado_minimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materiales_habilitados', to='usuarios.grado'),
        ),
        migrations.AddField(
            model_name='visualizacionmaterial',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vistas_biblioteca', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='visualizacionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visualizaciones', to='biblioteca.materialestudio'),
        ),
        migrations.AlterUniqueTogether(
            name='visualizacionmaterial',
            unique_together={('alumno', 'material')},
        ),
    ]
