# Generated by Django 5.2.5 on 2026-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialestudio',
            name='descargable',
            field=models.BooleanField(default=True, verbose_name='Permitir Descarga'),
        ),
        migrations.AlterModelTable(
            name='categoriacontenido',
            table='core_categoriacontenido',
        ),
    ]
